---
- name: checkout, customize and deploy coala-projects
  hosts: all
  become_user: freifunk
  vars:
    install_user: "{{ install_user }}"
    install_path: "{{ install_path }}"
  become_user: "{{ install_user }}"
  roles:
  - install_prerequisites
  - deploy_coala
