---
- name: checkout projects
- git:
    repo: https://github.com/freifunk/projects
    dest: "{{ install_path }}/website"

- name: delete collections
  file:
    path: "{{ install_path }}/website/{{ item }}"
    state: absent
  with_items:
    - _faq
    - _projects

- name: copy custom collections
  copy:
    src: "{{ item }}"
    dest: "{{ install_path }}/website/"
  with_items:
    - collections/_faq
    - collection/_projects

- name: copy partial files
  copy:
    src: "{{ item }}"
    dest: "{{ install_path }}/website/partials"
  with_items:
    - _faq
    - _projects

- name: build jekyll site
