---
- name: checkout projects
  git:
    repo: https://github.com/freifunk/projects
    dest: "{{ install_path }}"
    force: yes

- name: delete collections
  file:
    path: "{{ install_path }}/{{ item }}"
    state: absent
  with_items:
    - _faq
    - _projects

- name: copy custom collections
  copy:
    src: "../{{ item }}"
    dest: "{{ install_path }}/"
  with_items:
    - collections/_faq
    - collections/_projects
    - data
    - partials

- name: install jekyll deps
  command: bundle install chdir="{{ install_path}}/"

- name: build jekyll site
  command: bundle exec jekyll build chdir="{{ install_path}}/"
